/*
 * Autogenerated from table.json from https://syscalls.mebeim.net/.
 * Kernel version: v6.17.
 * Architecture: x86 (64-bit), x64 (64-bit ABI).
 */
#ifndef LITRACE_SYSCALL_SCHEMA_H
#define LITRACE_SYSCALL_SCHEMA_H

#define __NR_read 0
#define __NR_write 1
#define __NR_open 2
#define __NR_close 3
#define __NR_newstat 4
#define __NR_newfstat 5
#define __NR_newlstat 6
#define __NR_poll 7
#define __NR_lseek 8
#define __NR_mmap 9
#define __NR_mprotect 10
#define __NR_munmap 11
#define __NR_brk 12
#define __NR_rt_sigaction 13
#define __NR_rt_sigprocmask 14
#define __NR_rt_sigreturn 15
#define __NR_ioctl 16
#define __NR_pread64 17
#define __NR_pwrite64 18
#define __NR_readv 19
#define __NR_writev 20
#define __NR_access 21
#define __NR_pipe 22
#define __NR_select 23
#define __NR_sched_yield 24
#define __NR_mremap 25
#define __NR_msync 26
#define __NR_mincore 27
#define __NR_madvise 28
#define __NR_shmget 29
#define __NR_shmat 30
#define __NR_shmctl 31
#define __NR_dup 32
#define __NR_dup2 33
#define __NR_pause 34
#define __NR_nanosleep 35
#define __NR_getitimer 36
#define __NR_alarm 37
#define __NR_setitimer 38
#define __NR_getpid 39
#define __NR_sendfile64 40
#define __NR_socket 41
#define __NR_connect 42
#define __NR_accept 43
#define __NR_sendto 44
#define __NR_recvfrom 45
#define __NR_sendmsg 46
#define __NR_recvmsg 47
#define __NR_shutdown 48
#define __NR_bind 49
#define __NR_listen 50
#define __NR_getsockname 51
#define __NR_getpeername 52
#define __NR_socketpair 53
#define __NR_setsockopt 54
#define __NR_getsockopt 55
#define __NR_clone 56
#define __NR_fork 57
#define __NR_vfork 58
#define __NR_execve 59
#define __NR_exit 60
#define __NR_wait4 61
#define __NR_kill 62
#define __NR_newuname 63
#define __NR_semget 64
#define __NR_semop 65
#define __NR_semctl 66
#define __NR_shmdt 67
#define __NR_msgget 68
#define __NR_msgsnd 69
#define __NR_msgrcv 70
#define __NR_msgctl 71
#define __NR_fcntl 72
#define __NR_flock 73
#define __NR_fsync 74
#define __NR_fdatasync 75
#define __NR_truncate 76
#define __NR_ftruncate 77
#define __NR_getdents 78
#define __NR_getcwd 79
#define __NR_chdir 80
#define __NR_fchdir 81
#define __NR_rename 82
#define __NR_mkdir 83
#define __NR_rmdir 84
#define __NR_creat 85
#define __NR_link 86
#define __NR_unlink 87
#define __NR_symlink 88
#define __NR_readlink 89
#define __NR_chmod 90
#define __NR_fchmod 91
#define __NR_chown 92
#define __NR_fchown 93
#define __NR_lchown 94
#define __NR_umask 95
#define __NR_gettimeofday 96
#define __NR_getrlimit 97
#define __NR_getrusage 98
#define __NR_sysinfo 99
#define __NR_times 100
#define __NR_ptrace 101
#define __NR_getuid 102
#define __NR_syslog 103
#define __NR_getgid 104
#define __NR_setuid 105
#define __NR_setgid 106
#define __NR_geteuid 107
#define __NR_getegid 108
#define __NR_setpgid 109
#define __NR_getppid 110
#define __NR_getpgrp 111
#define __NR_setsid 112
#define __NR_setreuid 113
#define __NR_setregid 114
#define __NR_getgroups 115
#define __NR_setgroups 116
#define __NR_setresuid 117
#define __NR_getresuid 118
#define __NR_setresgid 119
#define __NR_getresgid 120
#define __NR_getpgid 121
#define __NR_setfsuid 122
#define __NR_setfsgid 123
#define __NR_getsid 124
#define __NR_capget 125
#define __NR_capset 126
#define __NR_rt_sigpending 127
#define __NR_rt_sigtimedwait 128
#define __NR_rt_sigqueueinfo 129
#define __NR_rt_sigsuspend 130
#define __NR_sigaltstack 131
#define __NR_utime 132
#define __NR_mknod 133
#define __NR_personality 135
#define __NR_ustat 136
#define __NR_statfs 137
#define __NR_fstatfs 138
#define __NR_sysfs 139
#define __NR_getpriority 140
#define __NR_setpriority 141
#define __NR_sched_setparam 142
#define __NR_sched_getparam 143
#define __NR_sched_setscheduler 144
#define __NR_sched_getscheduler 145
#define __NR_sched_get_priority_max 146
#define __NR_sched_get_priority_min 147
#define __NR_sched_rr_get_interval 148
#define __NR_mlock 149
#define __NR_munlock 150
#define __NR_mlockall 151
#define __NR_munlockall 152
#define __NR_vhangup 153
#define __NR_modify_ldt 154
#define __NR_pivot_root 155
#define __NR_prctl 157
#define __NR_arch_prctl 158
#define __NR_adjtimex 159
#define __NR_setrlimit 160
#define __NR_chroot 161
#define __NR_sync 162
#define __NR_acct 163
#define __NR_settimeofday 164
#define __NR_mount 165
#define __NR_umount 166
#define __NR_swapon 167
#define __NR_swapoff 168
#define __NR_reboot 169
#define __NR_sethostname 170
#define __NR_setdomainname 171
#define __NR_iopl 172
#define __NR_ioperm 173
#define __NR_init_module 175
#define __NR_delete_module 176
#define __NR_quotactl 179
#define __NR_gettid 186
#define __NR_readahead 187
#define __NR_setxattr 188
#define __NR_lsetxattr 189
#define __NR_fsetxattr 190
#define __NR_getxattr 191
#define __NR_lgetxattr 192
#define __NR_fgetxattr 193
#define __NR_listxattr 194
#define __NR_llistxattr 195
#define __NR_flistxattr 196
#define __NR_removexattr 197
#define __NR_lremovexattr 198
#define __NR_fremovexattr 199
#define __NR_tkill 200
#define __NR_time 201
#define __NR_futex 202
#define __NR_sched_setaffinity 203
#define __NR_sched_getaffinity 204
#define __NR_io_setup 206
#define __NR_io_destroy 207
#define __NR_io_getevents 208
#define __NR_io_submit 209
#define __NR_io_cancel 210
#define __NR_epoll_create 213
#define __NR_remap_file_pages 216
#define __NR_getdents64 217
#define __NR_set_tid_address 218
#define __NR_restart_syscall 219
#define __NR_semtimedop 220
#define __NR_fadvise64 221
#define __NR_timer_create 222
#define __NR_timer_settime 223
#define __NR_timer_gettime 224
#define __NR_timer_getoverrun 225
#define __NR_timer_delete 226
#define __NR_clock_settime 227
#define __NR_clock_gettime 228
#define __NR_clock_getres 229
#define __NR_clock_nanosleep 230
#define __NR_exit_group 231
#define __NR_epoll_wait 232
#define __NR_epoll_ctl 233
#define __NR_tgkill 234
#define __NR_utimes 235
#define __NR_mbind 237
#define __NR_set_mempolicy 238
#define __NR_get_mempolicy 239
#define __NR_mq_open 240
#define __NR_mq_unlink 241
#define __NR_mq_timedsend 242
#define __NR_mq_timedreceive 243
#define __NR_mq_notify 244
#define __NR_mq_getsetattr 245
#define __NR_kexec_load 246
#define __NR_waitid 247
#define __NR_add_key 248
#define __NR_request_key 249
#define __NR_keyctl 250
#define __NR_ioprio_set 251
#define __NR_ioprio_get 252
#define __NR_inotify_init 253
#define __NR_inotify_add_watch 254
#define __NR_inotify_rm_watch 255
#define __NR_migrate_pages 256
#define __NR_openat 257
#define __NR_mkdirat 258
#define __NR_mknodat 259
#define __NR_fchownat 260
#define __NR_futimesat 261
#define __NR_newfstatat 262
#define __NR_unlinkat 263
#define __NR_renameat 264
#define __NR_linkat 265
#define __NR_symlinkat 266
#define __NR_readlinkat 267
#define __NR_fchmodat 268
#define __NR_faccessat 269
#define __NR_pselect6 270
#define __NR_ppoll 271
#define __NR_unshare 272
#define __NR_set_robust_list 273
#define __NR_get_robust_list 274
#define __NR_splice 275
#define __NR_tee 276
#define __NR_sync_file_range 277
#define __NR_vmsplice 278
#define __NR_move_pages 279
#define __NR_utimensat 280
#define __NR_epoll_pwait 281
#define __NR_signalfd 282
#define __NR_timerfd_create 283
#define __NR_eventfd 284
#define __NR_fallocate 285
#define __NR_timerfd_settime 286
#define __NR_timerfd_gettime 287
#define __NR_accept4 288
#define __NR_signalfd4 289
#define __NR_eventfd2 290
#define __NR_epoll_create1 291
#define __NR_dup3 292
#define __NR_pipe2 293
#define __NR_inotify_init1 294
#define __NR_preadv 295
#define __NR_pwritev 296
#define __NR_rt_tgsigqueueinfo 297
#define __NR_perf_event_open 298
#define __NR_recvmmsg 299
#define __NR_fanotify_init 300
#define __NR_fanotify_mark 301
#define __NR_prlimit64 302
#define __NR_name_to_handle_at 303
#define __NR_open_by_handle_at 304
#define __NR_clock_adjtime 305
#define __NR_syncfs 306
#define __NR_sendmmsg 307
#define __NR_setns 308
#define __NR_getcpu 309
#define __NR_process_vm_readv 310
#define __NR_process_vm_writev 311
#define __NR_kcmp 312
#define __NR_finit_module 313
#define __NR_sched_setattr 314
#define __NR_sched_getattr 315
#define __NR_renameat2 316
#define __NR_seccomp 317
#define __NR_getrandom 318
#define __NR_memfd_create 319
#define __NR_kexec_file_load 320
#define __NR_bpf 321
#define __NR_execveat 322
#define __NR_userfaultfd 323
#define __NR_membarrier 324
#define __NR_mlock2 325
#define __NR_copy_file_range 326
#define __NR_preadv2 327
#define __NR_pwritev2 328
#define __NR_pkey_mprotect 329
#define __NR_pkey_alloc 330
#define __NR_pkey_free 331
#define __NR_statx 332
#define __NR_io_pgetevents 333
#define __NR_rseq 334
#define __NR_uretprobe 335
#define __NR_pidfd_send_signal 424
#define __NR_io_uring_setup 425
#define __NR_io_uring_enter 426
#define __NR_io_uring_register 427
#define __NR_open_tree 428
#define __NR_move_mount 429
#define __NR_fsopen 430
#define __NR_fsconfig 431
#define __NR_fsmount 432
#define __NR_fspick 433
#define __NR_pidfd_open 434
#define __NR_clone3 435
#define __NR_close_range 436
#define __NR_openat2 437
#define __NR_pidfd_getfd 438
#define __NR_faccessat2 439
#define __NR_process_madvise 440
#define __NR_epoll_pwait2 441
#define __NR_mount_setattr 442
#define __NR_quotactl_fd 443
#define __NR_landlock_create_ruleset 444
#define __NR_landlock_add_rule 445
#define __NR_landlock_restrict_self 446
#define __NR_memfd_secret 447
#define __NR_process_mrelease 448
#define __NR_futex_waitv 449
#define __NR_set_mempolicy_home_node 450
#define __NR_cachestat 451
#define __NR_fchmodat2 452
#define __NR_map_shadow_stack 453
#define __NR_futex_wake 454
#define __NR_futex_wait 455
#define __NR_futex_requeue 456
#define __NR_statmount 457
#define __NR_listmount 458
#define __NR_lsm_get_self_attr 459
#define __NR_lsm_set_self_attr 460
#define __NR_lsm_list_modules 461
#define __NR_mseal 462
#define __NR_setxattrat 463
#define __NR_getxattrat 464
#define __NR_listxattrat 465
#define __NR_removexattrat 466
#define __NR_open_tree_attr 467
#define __NR_file_getattr 468
#define __NR_file_setattr 469

static const struct syscall_arg_schema syscall_schemas[] = {
	{
	 .syscall_id = __NR_read,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, VAR_ARG_BYTES, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_write,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, VAR_ARG_BYTES, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_open,
	 .arg_count = 3,
	 .arg_types = {VAR_ARG_STRING, ARG_FLAGS, ARG_MODE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_close,
	 .arg_count = 1,
	 .arg_types = {ARG_FD, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_newstat,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_newfstat,
	 .arg_count = 2,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_newlstat,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_poll,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_FD, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_lseek,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_OFF, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mmap,
	 .arg_count = 6,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_UINT, ARG_UINT, ARG_FD, ARG_UINT},
	 },
	{
	 .syscall_id = __NR_mprotect,
	 .arg_count = 3,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_munmap,
	 .arg_count = 2,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_brk,
	 .arg_count = 1,
	 .arg_types = {ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_rt_sigaction,
	 .arg_count = 4,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_rt_sigprocmask,
	 .arg_count = 4,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_rt_sigreturn,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_ioctl,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_pread64,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_UINT, ARG_OFF, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_pwrite64,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_UINT, ARG_OFF, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_readv,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_writev,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_access,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_MODE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_pipe,
	 .arg_count = 1,
	 .arg_types = {ARG_FD, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_select,
	 .arg_count = 5,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_PTR, ARG_PTR, ARG_PTR, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sched_yield,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mremap,
	 .arg_count = 5,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_UINT, ARG_UINT, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_msync,
	 .arg_count = 3,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mincore,
	 .arg_count = 3,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_madvise,
	 .arg_count = 3,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_shmget,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_UINT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_shmat,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, VAR_ARG_STRING, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_shmctl,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_dup,
	 .arg_count = 1,
	 .arg_types = {ARG_FD, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_dup2,
	 .arg_count = 2,
	 .arg_types = {ARG_FD, ARG_FD, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_pause,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_nanosleep,
	 .arg_count = 2,
	 .arg_types = {ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getitimer,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_alarm,
	 .arg_count = 1,
	 .arg_types = {ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setitimer,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getpid,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sendfile64,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_FD, ARG_OFF, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_socket,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_connect,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_accept,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sendto,
	 .arg_count = 6,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_UINT, ARG_PTR, ARG_INT},
	 },
	{
	 .syscall_id = __NR_recvfrom,
	 .arg_count = 6,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_UINT, ARG_PTR, ARG_PTR},
	 },
	{
	 .syscall_id = __NR_sendmsg,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_recvmsg,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_shutdown,
	 .arg_count = 2,
	 .arg_types = {ARG_FD, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_bind,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_listen,
	 .arg_count = 2,
	 .arg_types = {ARG_FD, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getsockname,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getpeername,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_socketpair,
	 .arg_count = 4,
	 .arg_types = {ARG_INT, ARG_INT, ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setsockopt,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, ARG_INT, ARG_INT, VAR_ARG_STRING, ARG_INT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getsockopt,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, ARG_INT, ARG_INT, VAR_ARG_STRING, ARG_PTR, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_clone,
	 .arg_count = 5,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_PTR, ARG_PTR, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fork,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_vfork,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_execve,
	 .arg_count = 3,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_ARGV, VAR_ARG_ARGV, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_exit,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_wait4,
	 .arg_count = 4,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_kill,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_newuname,
	 .arg_count = 1,
	 .arg_types = {ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_semget,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_semop,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_semctl,
	 .arg_count = 4,
	 .arg_types = {ARG_INT, ARG_INT, ARG_INT, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_shmdt,
	 .arg_count = 1,
	 .arg_types = {VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_msgget,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_msgsnd,
	 .arg_count = 4,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_UINT, ARG_INT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_msgrcv,
	 .arg_count = 5,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_UINT, ARG_UINT, ARG_INT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_msgctl,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fcntl,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_flock,
	 .arg_count = 2,
	 .arg_types = {ARG_FD, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fsync,
	 .arg_count = 1,
	 .arg_types = {ARG_FD, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fdatasync,
	 .arg_count = 1,
	 .arg_types = {ARG_FD, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_truncate,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_ftruncate,
	 .arg_count = 2,
	 .arg_types = {ARG_FD, ARG_OFF, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getdents,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getcwd,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_chdir,
	 .arg_count = 1,
	 .arg_types = {VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fchdir,
	 .arg_count = 1,
	 .arg_types = {ARG_FD, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_rename,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mkdir,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_MODE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_rmdir,
	 .arg_count = 1,
	 .arg_types = {VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_creat,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_MODE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_link,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_unlink,
	 .arg_count = 1,
	 .arg_types = {VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_symlink,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_readlink,
	 .arg_count = 3,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_chmod,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_MODE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fchmod,
	 .arg_count = 2,
	 .arg_types = {ARG_FD, ARG_MODE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_chown,
	 .arg_count = 3,
	 .arg_types = {VAR_ARG_STRING, ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fchown,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_lchown,
	 .arg_count = 3,
	 .arg_types = {VAR_ARG_STRING, ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_umask,
	 .arg_count = 1,
	 .arg_types = {ARG_MODE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_gettimeofday,
	 .arg_count = 2,
	 .arg_types = {ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getrlimit,
	 .arg_count = 2,
	 .arg_types = {ARG_UINT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getrusage,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sysinfo,
	 .arg_count = 1,
	 .arg_types = {ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_times,
	 .arg_count = 1,
	 .arg_types = {ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_ptrace,
	 .arg_count = 4,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getuid,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_syslog,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, VAR_ARG_STRING, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getgid,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setuid,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setgid,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_geteuid,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getegid,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setpgid,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getppid,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getpgrp,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setsid,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setreuid,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setregid,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getgroups,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setgroups,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setresuid,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getresuid,
	 .arg_count = 3,
	 .arg_types = {ARG_PTR, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setresgid,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getresgid,
	 .arg_count = 3,
	 .arg_types = {ARG_PTR, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getpgid,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setfsuid,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setfsgid,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getsid,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_capget,
	 .arg_count = 2,
	 .arg_types = {ARG_RAW, ARG_RAW, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_capset,
	 .arg_count = 2,
	 .arg_types = {ARG_RAW, ARG_RAW, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_rt_sigpending,
	 .arg_count = 2,
	 .arg_types = {ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_rt_sigtimedwait,
	 .arg_count = 4,
	 .arg_types = {ARG_PTR, ARG_PTR, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_rt_sigqueueinfo,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_rt_sigsuspend,
	 .arg_count = 2,
	 .arg_types = {ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sigaltstack,
	 .arg_count = 2,
	 .arg_types = {ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_utime,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mknod,
	 .arg_count = 3,
	 .arg_types = {VAR_ARG_STRING, ARG_MODE, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_personality,
	 .arg_count = 1,
	 .arg_types = {ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_ustat,
	 .arg_count = 2,
	 .arg_types = {ARG_UINT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_statfs,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fstatfs,
	 .arg_count = 2,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sysfs,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getpriority,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setpriority,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sched_setparam,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sched_getparam,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sched_setscheduler,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sched_getscheduler,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sched_get_priority_max,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sched_get_priority_min,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sched_rr_get_interval,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mlock,
	 .arg_count = 2,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_munlock,
	 .arg_count = 2,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mlockall,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_munlockall,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_vhangup,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_modify_ldt,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_pivot_root,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_prctl,
	 .arg_count = 5,
	 .arg_types = {ARG_INT, ARG_UINT, ARG_UINT, ARG_UINT, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_arch_prctl,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_adjtimex,
	 .arg_count = 1,
	 .arg_types = {ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setrlimit,
	 .arg_count = 2,
	 .arg_types = {ARG_UINT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_chroot,
	 .arg_count = 1,
	 .arg_types = {VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sync,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_acct,
	 .arg_count = 1,
	 .arg_types = {VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_settimeofday,
	 .arg_count = 2,
	 .arg_types = {ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mount,
	 .arg_count = 5,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, VAR_ARG_STRING, ARG_UINT, ARG_PTR, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_umount,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_swapon,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_swapoff,
	 .arg_count = 1,
	 .arg_types = {VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_reboot,
	 .arg_count = 4,
	 .arg_types = {ARG_INT, ARG_INT, ARG_UINT, ARG_PTR, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sethostname,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setdomainname,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_iopl,
	 .arg_count = 1,
	 .arg_types = {ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_ioperm,
	 .arg_count = 3,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_init_module,
	 .arg_count = 3,
	 .arg_types = {ARG_PTR, ARG_UINT, VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_delete_module,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_quotactl,
	 .arg_count = 4,
	 .arg_types = {ARG_UINT, VAR_ARG_STRING, ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_gettid,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_readahead,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_OFF, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setxattr,
	 .arg_count = 5,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, ARG_PTR, ARG_UINT, ARG_INT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_lsetxattr,
	 .arg_count = 5,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, ARG_PTR, ARG_UINT, ARG_INT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fsetxattr,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_PTR, ARG_UINT, ARG_INT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getxattr,
	 .arg_count = 4,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_lgetxattr,
	 .arg_count = 4,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fgetxattr,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_listxattr,
	 .arg_count = 3,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_llistxattr,
	 .arg_count = 3,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_flistxattr,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_removexattr,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_lremovexattr,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fremovexattr,
	 .arg_count = 2,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_tkill,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_time,
	 .arg_count = 1,
	 .arg_types = {ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_futex,
	 .arg_count = 6,
	 .arg_types = {ARG_PTR, ARG_INT, ARG_UINT, ARG_PTR, ARG_PTR, ARG_UINT},
	 },
	{
	 .syscall_id = __NR_sched_setaffinity,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_UINT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sched_getaffinity,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_UINT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_io_setup,
	 .arg_count = 2,
	 .arg_types = {ARG_UINT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_io_destroy,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_io_getevents,
	 .arg_count = 5,
	 .arg_types = {ARG_INT, ARG_UINT, ARG_UINT, ARG_PTR, ARG_PTR, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_io_submit,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_UINT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_io_cancel,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_epoll_create,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_remap_file_pages,
	 .arg_count = 5,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_UINT, ARG_UINT, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getdents64,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_set_tid_address,
	 .arg_count = 1,
	 .arg_types = {ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_restart_syscall,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_semtimedop,
	 .arg_count = 4,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_UINT, ARG_PTR, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fadvise64,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_OFF, ARG_UINT, ARG_INT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_timer_create,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_timer_settime,
	 .arg_count = 4,
	 .arg_types = {ARG_INT, ARG_INT, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_timer_gettime,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_timer_getoverrun,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_timer_delete,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_clock_settime,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_clock_gettime,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_clock_getres,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_clock_nanosleep,
	 .arg_count = 4,
	 .arg_types = {ARG_INT, ARG_INT, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_exit_group,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_epoll_wait,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_INT, ARG_INT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_epoll_ctl,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_INT, ARG_FD, ARG_PTR, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_tgkill,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_utimes,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mbind,
	 .arg_count = 6,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_MODE, ARG_PTR, ARG_UINT, ARG_UINT},
	 },
	{
	 .syscall_id = __NR_set_mempolicy,
	 .arg_count = 3,
	 .arg_types = {ARG_MODE, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_get_mempolicy,
	 .arg_count = 5,
	 .arg_types = {ARG_PTR, ARG_PTR, ARG_UINT, ARG_UINT, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mq_open,
	 .arg_count = 4,
	 .arg_types = {VAR_ARG_STRING, ARG_INT, ARG_MODE, ARG_PTR, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mq_unlink,
	 .arg_count = 1,
	 .arg_types = {VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mq_timedsend,
	 .arg_count = 5,
	 .arg_types = {ARG_INT, VAR_ARG_STRING, ARG_UINT, ARG_UINT, ARG_PTR, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mq_timedreceive,
	 .arg_count = 5,
	 .arg_types = {ARG_INT, VAR_ARG_STRING, ARG_UINT, ARG_PTR, ARG_PTR, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mq_notify,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mq_getsetattr,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_kexec_load,
	 .arg_count = 4,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_waitid,
	 .arg_count = 5,
	 .arg_types = {ARG_INT, ARG_INT, ARG_PTR, ARG_INT, ARG_PTR, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_add_key,
	 .arg_count = 5,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, ARG_PTR, ARG_UINT, ARG_RAW, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_request_key,
	 .arg_count = 4,
	 .arg_types = {VAR_ARG_STRING, VAR_ARG_STRING, VAR_ARG_STRING, ARG_RAW, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_keyctl,
	 .arg_count = 5,
	 .arg_types = {ARG_INT, ARG_UINT, ARG_UINT, ARG_UINT, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_ioprio_set,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_ioprio_get,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_inotify_init,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_inotify_add_watch,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_MODE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_inotify_rm_watch,
	 .arg_count = 2,
	 .arg_types = {ARG_FD, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_migrate_pages,
	 .arg_count = 4,
	 .arg_types = {ARG_INT, ARG_UINT, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_openat,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_FLAGS, ARG_MODE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mkdirat,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_MODE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mknodat,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_MODE, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fchownat,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_INT, ARG_INT, ARG_INT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_futimesat,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_newfstatat,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_PTR, ARG_INT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_unlinkat,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_renameat,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_FD, VAR_ARG_STRING, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_linkat,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_FD, VAR_ARG_STRING, ARG_INT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_symlinkat,
	 .arg_count = 3,
	 .arg_types = {VAR_ARG_STRING, ARG_FD, VAR_ARG_STRING, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_readlinkat,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, VAR_ARG_STRING, ARG_INT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fchmodat,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_MODE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_faccessat,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_MODE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_pselect6,
	 .arg_count = 6,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_PTR, ARG_PTR, ARG_PTR, ARG_PTR},
	 },
	{
	 .syscall_id = __NR_ppoll,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, ARG_FD, ARG_PTR, ARG_PTR, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_unshare,
	 .arg_count = 1,
	 .arg_types = {ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_set_robust_list,
	 .arg_count = 2,
	 .arg_types = {ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_get_robust_list,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_splice,
	 .arg_count = 6,
	 .arg_types = {ARG_FD, ARG_OFF, ARG_FD, ARG_OFF, ARG_UINT, ARG_UINT},
	 },
	{
	 .syscall_id = __NR_tee,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_FD, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sync_file_range,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_OFF, ARG_OFF, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_vmsplice,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_move_pages,
	 .arg_count = 6,
	 .arg_types = {ARG_INT, ARG_UINT, ARG_PTR, ARG_PTR, ARG_PTR, ARG_INT},
	 },
	{
	 .syscall_id = __NR_utimensat,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_PTR, ARG_INT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_epoll_pwait,
	 .arg_count = 6,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_INT, ARG_INT, ARG_PTR, ARG_UINT},
	 },
	{
	 .syscall_id = __NR_signalfd,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_timerfd_create,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_eventfd,
	 .arg_count = 1,
	 .arg_types = {ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fallocate,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_MODE, ARG_OFF, ARG_OFF, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_timerfd_settime,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_INT, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_timerfd_gettime,
	 .arg_count = 2,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_accept4,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_PTR, ARG_INT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_signalfd4,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_INT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_eventfd2,
	 .arg_count = 2,
	 .arg_types = {ARG_UINT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_epoll_create1,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_dup3,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_FD, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_pipe2,
	 .arg_count = 2,
	 .arg_types = {ARG_FD, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_inotify_init1,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_preadv,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_UINT, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_pwritev,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_UINT, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_rt_tgsigqueueinfo,
	 .arg_count = 4,
	 .arg_types = {ARG_INT, ARG_INT, ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_perf_event_open,
	 .arg_count = 5,
	 .arg_types = {ARG_PTR, ARG_INT, ARG_INT, ARG_FD, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_recvmmsg,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_UINT, ARG_PTR, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fanotify_init,
	 .arg_count = 2,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fanotify_mark,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, ARG_UINT, ARG_MODE, ARG_FD, VAR_ARG_STRING, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_prlimit64,
	 .arg_count = 4,
	 .arg_types = {ARG_INT, ARG_UINT, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_name_to_handle_at,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_PTR, ARG_PTR, ARG_INT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_open_by_handle_at,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_clock_adjtime,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_syncfs,
	 .arg_count = 1,
	 .arg_types = {ARG_FD, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sendmmsg,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setns,
	 .arg_count = 2,
	 .arg_types = {ARG_FD, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getcpu,
	 .arg_count = 3,
	 .arg_types = {ARG_PTR, ARG_PTR, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_process_vm_readv,
	 .arg_count = 6,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_UINT, ARG_PTR, ARG_UINT, ARG_UINT},
	 },
	{
	 .syscall_id = __NR_process_vm_writev,
	 .arg_count = 6,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_UINT, ARG_PTR, ARG_UINT, ARG_UINT},
	 },
	{
	 .syscall_id = __NR_kcmp,
	 .arg_count = 5,
	 .arg_types = {ARG_INT, ARG_INT, ARG_INT, ARG_UINT, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_finit_module,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sched_setattr,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_sched_getattr,
	 .arg_count = 4,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_renameat2,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_FD, VAR_ARG_STRING, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_seccomp,
	 .arg_count = 3,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_getrandom,
	 .arg_count = 3,
	 .arg_types = {VAR_ARG_STRING, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_memfd_create,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_kexec_file_load,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, ARG_FD, ARG_UINT, VAR_ARG_STRING, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_bpf,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_execveat,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, VAR_ARG_ARGV, VAR_ARG_ARGV, ARG_INT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_userfaultfd,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_membarrier,
	 .arg_count = 3,
	 .arg_types = {ARG_INT, ARG_UINT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mlock2,
	 .arg_count = 3,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_copy_file_range,
	 .arg_count = 6,
	 .arg_types = {ARG_FD, ARG_OFF, ARG_FD, ARG_OFF, ARG_UINT, ARG_UINT},
	 },
	{
	 .syscall_id = __NR_preadv2,
	 .arg_count = 6,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_UINT, ARG_UINT, ARG_RAW},
	 },
	{
	 .syscall_id = __NR_pwritev2,
	 .arg_count = 6,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_UINT, ARG_UINT, ARG_RAW},
	 },
	{
	 .syscall_id = __NR_pkey_mprotect,
	 .arg_count = 4,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_UINT, ARG_INT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_pkey_alloc,
	 .arg_count = 2,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_pkey_free,
	 .arg_count = 1,
	 .arg_types = {ARG_INT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_statx,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_UINT, ARG_MODE, ARG_PTR, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_io_pgetevents,
	 .arg_count = 6,
	 .arg_types = {ARG_INT, ARG_UINT, ARG_UINT, ARG_PTR, ARG_PTR, ARG_PTR},
	 },
	{
	 .syscall_id = __NR_rseq,
	 .arg_count = 4,
	 .arg_types = {ARG_PTR, ARG_UINT, ARG_INT, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_uretprobe,
	 .arg_count = 0,
	 .arg_types = {ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_pidfd_send_signal,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_INT, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_io_uring_setup,
	 .arg_count = 2,
	 .arg_types = {ARG_UINT, ARG_PTR, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_io_uring_enter,
	 .arg_count = 6,
	 .arg_types = {ARG_FD, ARG_UINT, ARG_UINT, ARG_UINT, ARG_PTR, ARG_UINT},
	 },
	{
	 .syscall_id = __NR_io_uring_register,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_UINT, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_open_tree,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_move_mount,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_FD, VAR_ARG_STRING, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fsopen,
	 .arg_count = 2,
	 .arg_types = {VAR_ARG_STRING, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fsconfig,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, ARG_UINT, VAR_ARG_STRING, ARG_PTR, ARG_INT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fsmount,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fspick,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_pidfd_open,
	 .arg_count = 2,
	 .arg_types = {ARG_INT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_clone3,
	 .arg_count = 2,
	 .arg_types = {ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_close_range,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_FD, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_openat2,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_pidfd_getfd,
	 .arg_count = 3,
	 .arg_types = {ARG_FD, ARG_FD, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_faccessat2,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_MODE, ARG_INT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_process_madvise,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_UINT, ARG_INT, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_epoll_pwait2,
	 .arg_count = 6,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_INT, ARG_PTR, ARG_PTR, ARG_UINT},
	 },
	{
	 .syscall_id = __NR_mount_setattr,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_UINT, ARG_PTR, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_quotactl_fd,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_UINT, ARG_INT, ARG_PTR, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_landlock_create_ruleset,
	 .arg_count = 3,
	 .arg_types = {ARG_PTR, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_landlock_add_rule,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_RAW, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_landlock_restrict_self,
	 .arg_count = 2,
	 .arg_types = {ARG_FD, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_memfd_secret,
	 .arg_count = 1,
	 .arg_types = {ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_process_mrelease,
	 .arg_count = 2,
	 .arg_types = {ARG_FD, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_futex_waitv,
	 .arg_count = 5,
	 .arg_types = {ARG_PTR, ARG_UINT, ARG_UINT, ARG_PTR, ARG_INT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_set_mempolicy_home_node,
	 .arg_count = 4,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_cachestat,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, ARG_PTR, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_fchmodat2,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_MODE, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_map_shadow_stack,
	 .arg_count = 3,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_futex_wake,
	 .arg_count = 4,
	 .arg_types = {ARG_PTR, ARG_MODE, ARG_INT, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_futex_wait,
	 .arg_count = 6,
	 .arg_types = {ARG_PTR, ARG_UINT, ARG_MODE, ARG_UINT, ARG_PTR, ARG_INT},
	 },
	{
	 .syscall_id = __NR_futex_requeue,
	 .arg_count = 4,
	 .arg_types = {ARG_PTR, ARG_UINT, ARG_INT, ARG_INT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_statmount,
	 .arg_count = 4,
	 .arg_types = {ARG_PTR, ARG_PTR, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_listmount,
	 .arg_count = 4,
	 .arg_types = {ARG_PTR, ARG_PTR, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_lsm_get_self_attr,
	 .arg_count = 4,
	 .arg_types = {ARG_UINT, ARG_PTR, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_lsm_set_self_attr,
	 .arg_count = 4,
	 .arg_types = {ARG_UINT, ARG_PTR, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_lsm_list_modules,
	 .arg_count = 3,
	 .arg_types = {ARG_PTR, ARG_PTR, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_mseal,
	 .arg_count = 3,
	 .arg_types = {ARG_UINT, ARG_UINT, ARG_UINT, ARG_NONE, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_setxattrat,
	 .arg_count = 6,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_UINT, VAR_ARG_STRING, ARG_PTR, ARG_UINT},
	 },
	{
	 .syscall_id = __NR_getxattrat,
	 .arg_count = 6,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_UINT, VAR_ARG_STRING, ARG_PTR, ARG_UINT},
	 },
	{
	 .syscall_id = __NR_listxattrat,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_UINT, VAR_ARG_STRING, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_removexattrat,
	 .arg_count = 4,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_UINT, VAR_ARG_STRING, ARG_NONE, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_open_tree_attr,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_UINT, ARG_PTR, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_file_getattr,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_PTR, ARG_UINT, ARG_UINT, ARG_NONE},
	 },
	{
	 .syscall_id = __NR_file_setattr,
	 .arg_count = 5,
	 .arg_types = {ARG_FD, VAR_ARG_STRING, ARG_PTR, ARG_UINT, ARG_UINT, ARG_NONE},
	 },
};

#endif
